Revert "Fix missing f-string (#4150)"
This reverts commit 8d2c47cc40b170170c60d179a044ffdc0d46b2c6.

Error when running test:

```
  File "/usr/local/google/home/laurenzo/src/iree-build/bindings/python/pyiree/rt/system_api.py", line 88, in _create_default_iree_driver
    print(f"Created IREE driver {driver_name}: {driver:!r}", file=sys.stderr)
TypeError: unsupported format string passed to pyiree.rt.binding.HalDriver.__format__
```